python main.py \
  --run_name "bigcodebench-valtest-80-gpt-o3-mini-5-iters" \
  --root_dir "root" \
  --dataset_path ./benchmarks/valtest-variable/bigcodebench_80.jsonl \
  --strategy "reflexion" \
  --language "py" \
  --model "gpt-o3-mini" \
  --pass_at_k "1" \
  --max_iters "5" \
  --is_unit_test \
  --verbose
